name: Nuxt3 CI/CD Demo
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 使用别人封装好的的action，用于clone该仓库的源码到工作流中
      - name: Checkout
        uses: actions/checkout@v3
      # 在工作流中安装node环境（必需，这样才能在后续工作流程中运行 npm install 等指令，否则会报错）
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16 # 指定node版本
      # 打包代码生成环境
      - name: Build
        run: |
          npm install # 安装依赖
          npm run build # 打包前端代码到生产环境
      # 部署
      - name: Deploy
        uses: cross-the-world/scp-pipeline@master
        with:
          host: ${{ secrets.HOST }} # 服务器IP（需要在GitHub上自行配置对应的secret）
          user: ${{ secrets.HOST_USER }} # 服务器用户名
          pass: ${{ secrets.HOST_PASS }} # 服务器密码
          connect_timeout: 30s
          local: './.nuxt/*' # 源路径（工作流）
          remote: /www/wwwroot/cicd-nuxt3.zeroojs.com/app/.nuxt # 目标路径（服务器）
      # 在服务器端执行相关指令
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # 服务器IP（需要在GitHub上自行配置对应的secret）
          username: ${{ secrets.HOST_USER }} # 服务器用户名
          password: ${{ secrets.HOST_PASS }} # 服务器密码
          script: |
            cd /www/wwwroot/cicd-nuxt3.zeroojs.com/app # 进入服务器中的端工程所在的目录
            # export NODE_HOME=/www/server/nvm/versions/node/v14.17.0/bin/node  # 可使用`whereis node`查询node所在的目录
            # export PATH=$PATH:$NODE_HOME/bin # 重新定义node的环境变量（必需，这样才能在后续工作流程中运行 npm install 等指令，否则会报错）
            npm install # 安装项目依赖
            pm2 delete cicd_nuxt3_3005 # 删除旧的进程
            pm2 start --name cicd_nuxt3_3005 npm -- run start # 启动新的进程